-- 1. Count total events

SELECT
  COUNT(*) AS total_events
FROM
  analytics.events;



-- 2. Count events by type

SELECT
  event_type,
  COUNT(*) AS event_count
FROM
  analytics.events
GROUP BY
  event_type
ORDER BY
  event_count DESC;



-- 3. Revenue generated by product

SELECT
  product,
  SUM(amount) AS total_revenue
FROM
  analytics.events
WHERE
  event_type = 'purchase'
GROUP BY
  product
ORDER BY
  total_revenue DESC;



-- 4. Active users

SELECT
  user_id,
  COUNT(*) AS activity_count
FROM
  analytics.events
GROUP BY
  user_id
ORDER BY
  activity_count DESC;



-- 5. Real-time revenue by minute

SELECT
  TIMESTAMP_TRUNC(timestamp, MINUTE) AS event_minute,
  SUM(amount) AS revenue
FROM
  analytics.events
GROUP BY
  event_minute
ORDER BY
  event_minute;
